#server:
#  port: 8000
#spring:
#  application:
#    name: gateway
#  zipkin:
#    base-url: http://127.0.0.1:9411/ #zipkin地址
#    discovery-client-enabled: false  #不用开启服务发现
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    gateway:
#      discovery:
#        locator:
#          enabled: true  #开启网关拉取nacos的服务
#      routes:
#        - id: order-service  #路由唯一标识
#          uri: http://127.0.0.1:7000  #想要转发到的地址
#          predicates:
#            - Path=/order-server/**
#          filters:
#            - StripPrefix=1
