#server:
#  port: 9000
#spring:
#  application:
#    name: sales-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/cloud_video?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 111111
#  zipkin:
#    base-url: http://127.0.0.1:9411/ #zipkin地址
#    discovery-client-enabled: false  #不用开启服务发现
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比 默认为0.1，即10% 这里配置1，是记录全部的sleuth信息，是为了收集到更多的数据（仅供测试用）。 在分布式系统中，过于频繁的采样会影响系统性能，所以这里配置需要采用一个合适的值。
#
#  #nacos配置
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:6060
#        port: 6080
#  #格式化日期格式
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
## 控制台输出sql、下划线转驼峰
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true